#!/usr/bin/env python3
from __future__ import annotations
import pathlib, sys
MARKER = "<!-- voxel-resource-loading-strategy-ui -->"
UI = r'''
<!-- voxel-resource-loading-strategy-ui -->
<style>
#strategy-ui{position:fixed;z-index:10000;top:12px;left:12px;right:12px;max-width:980px;margin:auto;padding:18px;border:2px solid #43515f;border-radius:16px;background:rgba(5,14,23,.96);color:#f4f7fa;font:22px/1.35 system-ui,sans-serif;box-sizing:border-box}#strategy-ui.collapsed{left:auto;width:auto;padding:10px 14px}#strategy-ui.collapsed .body{display:none}#strategy-ui h1{font-size:30px;margin:0 0 8px}#strategy-ui .status{font-size:25px;font-weight:750;color:#4e91ff}#strategy-ui .ok{color:#5ce66e}#strategy-ui .fail{color:#ff5960}#strategy-ui button,#strategy-ui a{min-height:58px;padding:10px 16px;border:2px solid #3c8cff;border-radius:12px;background:#083a80;color:#fff;font:inherit;font-weight:700;text-decoration:none}#strategy-ui .secondary{background:#19222c;border-color:#526170}#strategy-ui .buttons{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}#strategy-ui table{width:100%;border-collapse:collapse;margin-top:12px;font-size:18px}#strategy-ui th,#strategy-ui td{padding:7px;border-bottom:1px solid #34404c;text-align:right}#strategy-ui th:first-child,#strategy-ui td:first-child{text-align:left}@media(max-width:700px){#strategy-ui{font-size:21px}#strategy-ui h1{font-size:28px}#strategy-ui .buttons{display:grid;grid-template-columns:1fr}#strategy-ui button,#strategy-ui a{width:100%}}
</style>
<div id="strategy-ui"><button id="collapse" class="secondary" style="float:right;min-height:48px">Collapse</button><div class="body"><h1>Resource Loading Strategy Comparison</h1><p>Same mobile Web runtime. Compares real terrain assets with trivial controls through synchronous and threaded ResourceLoader paths.</p><div id="status" class="status">Running automated comparison…</div><div id="summary"></div><div class="buttons"><button id="export" disabled>Export JSON</button><button id="rerun" class="secondary">Run Again</button><a href="../" class="secondary">Back to ResourceLoader Diagnostic</a></div><p style="font-size:18px;color:#bcc7d1">Keep this tab foregrounded until complete. The synchronous path yields between assets to keep the browser responsive.</p></div></div>
<script>(()=>{const root=document.getElementById('strategy-ui'),status=document.getElementById('status'),summary=document.getElementById('summary'),exp=document.getElementById('export');let payload=null;const med=v=>{v=[...v].sort((a,b)=>a-b);let m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2};const render=p=>{payload=p;const runs=p?.measured?.runs||[];const groups=new Map();for(const r of runs){const k=`${r.strategy}|${r.concurrency}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}let h='<table><tr><th>Strategy</th><th>C</th><th>Median batch</th><th>Median avg latency</th><th>Median throughput</th></tr>';for(const [k,g] of groups){const [s,c]=k.split('|');h+=`<tr><td>${s}</td><td>${c}</td><td>${med(g.map(r=>r.duration_msec)).toFixed(1)} ms</td><td>${med(g.map(r=>r.average_latency_msec)).toFixed(1)} ms</td><td>${med(g.map(r=>r.throughput_assets_per_second)).toFixed(1)}/s</td></tr>`}summary.innerHTML=h+'</table>';status.textContent=p.success?`Complete: ${runs.length} strategy runs.`:`Failed: ${p.failure||'unknown error'}`;status.className=p.success?'status ok':'status fail';exp.disabled=false};const poll=setInterval(()=>{if(window.__voxelResourceLoadingStrategyComparison){clearInterval(poll);render(window.__voxelResourceLoadingStrategyComparison)}},200);exp.onclick=()=>{if(!payload)return;const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='mobile-resource-loading-strategy-comparison.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),0)};document.getElementById('rerun').onclick=()=>location.reload();document.getElementById('collapse').onclick=e=>{root.classList.toggle('collapsed');e.target.textContent=root.classList.contains('collapsed')?'Show Experiment UI':'Collapse'}})();</script>
'''
def main():
    p=pathlib.Path(sys.argv[1]);t=p.read_text();
    if MARKER not in t:p.write_text(t.replace('</body>',UI+'\n</body>',1))
if __name__=='__main__':main()
